Add Homepage
hansderly/awesome-books pull request #1
Opened 2023-01-09 22:03 UTC by hansderly

In this PR, we:
- Added Linter configuration file
- Added project file and folder structure
- Added add book functionality
- Added remove book functionality
- Added localstorage for data persistency

2023-01-09 22:37 UTC, rloterh reviewed
Hi  Hans-Derly, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure to add a ReadMe to this project via [this link](https://github.com/microverseinc/readme-template), which should comply with the following standards:
- [ ] All main headers from the [ReadMe template](https://github.com/microverseinc/readme-template) should be present in your ReadMe, only the FAQ section is optional.
- [ ]  The _Future Features_ section of your ReadMe includes 1-3 potential features to be added later. 
- [ ] Kindly ensure to remove the Microverse template logo. Optionally, you can replace it with your own logo if you have one.
- [ ] Kindly ensure that provided text instructions are removed and filled in with custom content applicable to your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-10 01:19 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️ ♻️ ♻️

Hi Team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ You used Gitflow correctly 👍🏽
✅ Linter checks passed 👍🏽
✅ Used plain array and object for storing books 👍🏽
✅ Books are stored to localStorage correctly 👍🏽

## Required Changes ♻️
_Check the comments under the review._

- [ ] After the fix I suggested in the inline comment, I was able to save books and delete books. But when I refresh the browser, all books are cleared from the local storage. Kindly work on it so that when a book is stored in localStorage, even at browser refresh, the book should be there until it's deleted. Please consider working on that. 👍🏽

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-10 01:19 UTC, AmaduKamara commented on assets/scripts/book.js
> +form.addEventListener('submit', addBook);
- [ ] When I click the Add button to add a book, the app crashes. This is happening because there is no book to loop over at the moment and the console is giving an error on loading the books. Kindly work on that. 👍🏽

<img width="688" alt="Screenshot 2023-01-10 at 1 05 46 AM" src="https://user-images.githubusercontent.com/50941074/211438871-b6fd6931-c461-4e08-92ed-d636024279b3.png">

2023-01-10 01:19 UTC, AmaduKamara commented on assets/scripts/book.js
> +
[ Optional Change ]
I noticed that for the first launch of the app, there are no books in the library and you're looping over them.

- [ ] What if you could set an empty array to the books or the data fetched from local storage? Because, at the start, there are no books in localStorage but setting an initial, will fix the problem.

You could use this instead, `let library = [] || JSON.parse(data);`

When I used that, the problem was solved 👍🏽

2023-01-10 01:33 UTC, Reem-lab approved these changes
# Hi @hansderly, 👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media0.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif"/>

## Highlights
- No Linters error ✅
- Followed GitHub flow ✅
- Descriptive PR ✅
- Great working on the set up functionlaity ✅
- Professional README 🔥✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-10 01:35 UTC, merged